title: Rahul Nambiar
url: "https://rnambs.github.io"

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Portfolio"
   link: "portfolio"
 - name: "Resume"
   link: "Nambiar_2024.pdf"
 - name: "Contact"
   link: "contact"
