title: Rahul Nambiar
url: "https://rnambs.github.io"
baseurl: "/helloworld"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "This is based on jekyll website template. You can find the original template source code on GitHub."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About Me"
   link: "/helloworld"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
