title: Rahul Nambiar
url: "https://rnambs.github.io"
baseurl: "/me/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Portfolio"
   link: "portfolio"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
